<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="problemDetails.aspx.cs" Inherits="Healthcare.docInterface.WebForm4" %><asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">

    <%@ Import Namespace="System.Data" %>


    <style type="text/css">
        .style1
        {
            font-size: large;
            text-align: center;
        }
        .style2
        {
            font-size: large;
        }
        .style3
        {
            width: 288px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
  <script src="http://code.jquery.com/jquery-latest.js" type="text/javascript"></script>

   
   
<%
    DataTable dt = getAllData();
    int i = 1;
     %>
    <div>
        <font face="trebuchet ms,sans-serif" style="text-align: left ">
        <span class="style2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <img src="imgdata.aspx?patient_data_id=<%=dt.Rows[0]["patient_data_id"]%>" style="height: 589px; width: 601px" /><br />

        </span>

        </font>
    </div>
    <span class="style2">
    <a href="discussion.aspx?problem_id=<%=Request.Params["patient_data_id"] %>">DISCUSSION PAGE</a><br />
&nbsp;

<table style="border-width: thin; border-style: groove; width:100%; background-color: #FFFFCC; vertical-align: middle; text-align: left; font-weight: bold;">



        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                PARAMETERS</td>
            <td style="border: thin ridge #FFFFFF">
                CARE-SEEKER EXPLANATIONS</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Name (autogenerated)
            </td>
            <td style="border: thin ridge #FFFFFF"> <%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Age</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Gender</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Marital status and number of abortions/children (esp for female patients)&nbsp;&nbsp;</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                What is your main health issue?
            </td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Duration of complaint:</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Describe the problem:</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                To what degree is it interfering with your life</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Comments?</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Are you currently seeking any treatment for it (allopathic or alternative):</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Have you experienced similar problems in the past ?&nbsp;&nbsp;</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                If yes, did you take any treatment for it? Did it help?</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Have you had any major illnesses in the past which required hospitalization or a 
                trip to the physician</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                3. Any long term (chronic) health conditions you have been diagnosed with or on 
                treatment for (diabetes, heart conditions, HTN)</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Any allergies you are aware of ?</td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Does anyone in your immediate family have a similar condition (as your main 
                complaint)
            </td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                Does anyone in your family have any chronic health issue (HTN/CVS/CNS/Mental 
                health issues/Skin problems etc)
            </td>
            <td style="border: thin ridge #FFFFFF"><%=dt.Rows[0][i++] %>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" style="border: thin ridge #FFFFFF">
                &nbsp;</td>
            <td style="border: thin ridge #FFFFFF">
                &nbsp;</td>
        </tr>
   

    </table>

    
    <br />
    </span>
</asp:Content>
