<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="WebForm4.aspx.cs" Inherits="Healthcare.docInterface.WebForm4" %><asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">

<%@ Import Namespace="System.Data" %>


    <style type="text/css">
        .style1
        {
            font-size: large;
            text-align: center;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<%
    DataTable dt = getAllData();
    
    
 %>

    <div>
        <font face="trebuchet ms,sans-serif">1. Name (autogenerated)
        <br />
        </font>
    </div>
    <div>
        <font face="trebuchet ms,sans-serif">2. Age<br />
        <br />
        3. Gender (very important)<br />
        </font>
    </div>
    <div>
        <font face="trebuchet ms,sans-serif">4. Marital status and number of 
        abortions/children (esp for female patients)&nbsp;<br />
        </font>
    </div>
    <div>
        <font face="trebuchet ms,sans-serif">5.</font><span 
            style="font-family:'trebuchet ms',sans-serif">What is your main health issue<br />
        <br />
        </span>
    </div>
    <div>
        <font face="'trebuchet ms', sans-serif">6. Could you elaborate under the 
        following headings<br />
        </font>
    </div>
    <div>
        <font face="'trebuchet ms', sans-serif">a. Duration of complaint:<br />
        </font>
    </div>
    <div>
        <font face="'trebuchet ms', sans-serif">b. Describe the problem:<br />
        <br />
        </font>
    </div>
    <div>
        <font face="'trebuchet ms', sans-serif">c. To what degree is it interfering with 
        your life -
        <br />
        <br />
        Comments?<br />
        </font>
    </div>
    <div>
        <font face="'trebuchet ms', sans-serif">d. Are you currently seeking any 
        treatment for it (allopathic or alternative):<br />
        </font>
    </div>
    <div class="style1">
        <font face="'trebuchet ms', sans-serif">&nbsp;Past history</font></div>
    <div>
        <font face="'trebuchet ms', sans-serif">&nbsp;1. Have you experienced similar 
        problems in the past ?&nbsp;<br />
        <br />
        </font>
    </div>
    <div>
        <font face="'trebuchet ms', sans-serif">a. If yes, did you take any treatment 
        for it? Did it help?<br />
        <br />
        </font>
    </div>
    <div>
        <font face="'trebuchet ms', sans-serif">2. Have you had any major illnesses in 
        the past which required hospitalization or a trip to the physician<br />
        <br />
        </font>
    </div>
    <div>
        <font face="trebuchet ms,sans-serif">3. Any long term (chronic) health 
        conditions you have been diagnosed with or on treatment for (diabetes, heart 
        conditions, HTN)<br />
        <br />
        </font>
    </div>
    <div>
        <font face="trebuchet ms,sans-serif">4. Any allergies you are aware of ?<br />
        <br />
        </font>
    </div>
    <div>
        <font face="trebuchet ms,sans-serif">5. Does anyone in your immediate family 
        have a similar condition (as your main complaint)<br />
        <br />
        </font>
    </div>
    <div>
        <font face="trebuchet ms,sans-serif">6. Does anyone in your family have any 
        chronic health issue (HTN/CVS/CNS/Mental health issues/Skin problems etc)<br />
        <br />
        </font>
    </div>
    <p>
       
    </p>
</asp:Content>
