<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="careSeekersUI.aspx.cs" Inherits="Healthcare.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">



    <style type="text/css">
        .style1
        {
            font-size: x-large;
        }
        .style2
        {
            font-size: large;
            text-align: left;
        }
        .style3
        {
            text-align: center;
        }
        .style4
        {
            font-size: xx-large;
            text-align: left;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <p>
        <br />
        <span class="style1"><strong>CARE-SEEKERS: Submit your health data here.</strong></span></p>
    <asp:Panel ID="ImageUploadPanel" runat="server" Height="142px" 
        style="text-align: center">
        <span class="style2">
        Upload scanned image of narrative:<br />
        <br />
        </span>
        <asp:FileUpload ID="FileUpload1" runat="server" CssClass="style2" />
        <br />
        <br />
        <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
            style="margin-left: 0px" Text="Upload image ONLY ( less than 500KB )" 
            Width="263px" Visible="False" />
    </asp:Panel>
    <asp:Panel ID="FormQuestionsPanel" runat="server" Height="2033px" 
        style="text-align: center" Width="914px">
        <span class="style4">Fill narrative as a form :<br />
        </span>
        <span class="style2">
        <br />
        <div>
            <font face="trebuchet ms,sans-serif">1. Name (autogenerated)&nbsp; </font>
            <asp:TextBox ID="nameauto" runat="server" Width="314px" Visible="False"></asp:TextBox>
            &nbsp; <font face="trebuchet ms,sans-serif">&nbsp;<br />
            <br />
            &nbsp;2. Age : </font>
            <asp:TextBox ID="age" runat="server"></asp:TextBox>
            &nbsp;&nbsp;
            <br />
            <br />
            &nbsp;<font face="trebuchet ms,sans-serif">3. Gender (very important) :</font><asp:TextBox 
                ID="gender" runat="server"></asp:TextBox>
            <br />
            <br />
        </div>
        <div>
            <font face="trebuchet ms,sans-serif">4. Marital status and number of 
            abortions/children (esp for female patients)&nbsp;: </font>
            <asp:TextBox ID="marital" runat="server"></asp:TextBox>
            &nbsp;&nbsp;
            <br />
            <br />
        </div>
        <div>
            <font face="trebuchet ms,sans-serif">5.</font><span 
                style="font-family: 'trebuchet ms',sans-serif">What is your main health 
            issue: </span>
            <asp:TextBox ID="mainHealthIssue" runat="server"></asp:TextBox>
            &nbsp;
            <br />
            <br />
            6.</div>
        <div class="style3">
            <font face="'trebuchet ms', sans-serif">a. Duration of complaint<br />
            <br />
            </font>
            <asp:TextBox ID="duration" runat="server" Height="35px" 
                style="text-align: left" Width="232px" TextMode="MultiLine"></asp:TextBox>
            <span class="style2">&nbsp;&nbsp;&nbsp;
            <br />
            <br />
            &nbsp; <font face="'trebuchet ms', sans-serif">b. Describe the problem</font>&nbsp;&nbsp;
            <br />
            <br />
            &nbsp;
            <asp:TextBox ID="description" runat="server" Height="125px" Width="678px" 
                TextMode="MultiLine"></asp:TextBox>
            </span>
            <br />
            <br />
            <font face="'trebuchet ms', sans-serif" style="text-align: left">c. To what 
            degree is it interfering with your life -&nbsp;
            <br />
            <br />
            &nbsp;&nbsp;
            <asp:ListBox ID="degree1" runat="server" Height="73px" Width="139px">
                <asp:ListItem Value="Not-at-all">Not at all</asp:ListItem>
                <asp:ListItem>somewhat</asp:ListItem>
                <asp:ListItem>To a great extent</asp:ListItem>
            </asp:ListBox>
            <asp:ListBox ID="degree2" runat="server" Height="77px" Width="148px">
                <asp:ListItem>Physically</asp:ListItem>
                <asp:ListItem>Socially</asp:ListItem>
                <asp:ListItem>Financially</asp:ListItem>
            </asp:ListBox>
            <br />
            </font>
        </div>
        <div>
            <font face="'trebuchet ms', sans-serif">&nbsp;One blank field for comments if any&nbsp;&nbsp;&nbsp;
            </font>
            <asp:TextBox ID="comments" runat="server" Width="235px"></asp:TextBox>
            <br />
            <br />
        </div>
        <div>
            <font face="'trebuchet ms', sans-serif">d. Are you currently seeking any 
            treatment for it (allopathic or alternative)&nbsp;
            <asp:TextBox ID="treatment" runat="server" Height="21px" Width="213px"></asp:TextBox>
            <br />
            <br />
            e. What did the doctor say ?<br />&nbsp;
            <asp:TextBox ID="doctorSay" runat="server" Height="64px" TextMode="MultiLine" 
                Width="357px"></asp:TextBox>
            <br />
            <br />
            f. What drugs are you on?<asp:TextBox ID="drugsOn" runat="server" Height="21px" TextMode="MultiLine" 
                Width="688px"></asp:TextBox>
            <br />
            <strong>
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
            Past history<br /> </strong>
            </font>
        </div>
        <div>
            <font face="'trebuchet ms', sans-serif">&nbsp;1. Have you experienced similar 
            problems in the past ?&nbsp;</font><asp:TextBox ID="problemsInThePast" 
                runat="server" Width="168px"></asp:TextBox>
            <br />
            <br />
        </div>
        <div>
            <font face="'trebuchet ms', sans-serif">a. If yes, did you take any treatment 
            for it? Did it help? </font>
            <asp:TextBox ID="isTreatmentTaken" runat="server" Width="178px"></asp:TextBox>
            <br />
            <br />
        </div>
        <div>
            <font face="'trebuchet ms', sans-serif">2. Have you had any major illnesses in 
            the past which required hospitalization or a trip to the physician&nbsp;&nbsp;
            <br />
            <br />
            </font>
            <asp:TextBox ID="majorIllness" runat="server" Height="39px" 
                style="text-align: left" Width="292px"></asp:TextBox>
            <br />
        </div>
        <div>
            <font face="trebuchet ms,sans-serif">3. Any long term (chronic) health 
            conditions you have been diagnosed with or on treatment for (diabetes, heart 
            conditions, HTN)<br />
            <br />
            </font>
            <asp:TextBox ID="chronicIssue" runat="server" Height="47px" 
                style="text-align: justify" Width="549px" TextMode="MultiLine"></asp:TextBox>
            <br />
        </div>
        <div>
            <font face="trebuchet ms,sans-serif">4. Any allergies you are aware of ?&nbsp;&nbsp;
            <br />
            <asp:TextBox ID="allergies" runat="server" Height="62px" Width="301px" 
                TextMode="MultiLine"></asp:TextBox>
            <br />
            </font>
        </div>
        <div>
            <font face="trebuchet ms,sans-serif">5. Does anyone in your immediate family 
            have a similar condition (as your main complaint)<br />
            <br />
            </font>
            <asp:TextBox ID="familyMainComplaint" runat="server" Height="76px" 
                Width="309px" TextMode="MultiLine"></asp:TextBox>
            <br />
            <br />
        </div>
        <div style="height: 95px; margin-bottom: 0px">
            <font face="trebuchet ms,sans-serif">6. Does anyone in your family have any 
            chronic health issue (HTN/CVS/CNS/Mental health issues/Skin problems etc)<br />
            <br />
            </font>
            <asp:TextBox ID="familyChronic" runat="server" Height="89px" Width="362px"></asp:TextBox>
            <br />
            <br />
            <span class="style2">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="Button2" runat="server" onclick="Button2_Click" 
                style="text-align: center; height: 26px" Text="Submit health data" />
            </span>
        </div>
        </span>
    </asp:Panel>
    </asp:Content>
